### ISSUE TITLE
 request that the next new releases be released as soon as possible

### ISSUE THREAD

**Issue by 100vlx** [kvtools/etcdv3#3]
### Your feature request related to a problem? Please describe.

The current 1.0.2 version of the middleware references the obsolete `google.golang.org/grpc v1.38.0` library. 
I see that the go.mod of the master branch has been upgraded, so I request a new releases version.

### Describe the solution you'd like.

 request that the next new releases be released as soon as possible

### Describe alternatives you've considered.

 request that the next new releases be released as soon as possible

### Additional context.

![image](https://github.com/kvtools/etcdv3/assets/131951906/186aae7f-a381-47b2-9b3b-794683bc47ea)

**Comment by ldez** [comment]
Hello,

A new release is not required to update a dependency as a user of this library.
You just need to update the dependency on your project.

**Comment by 100vlx** [comment]
> Hello,
> 
> A new release is not required to update a dependency as a user of this library. You just need to update the dependency on your project.

I don't want this line in my project go.mod，
` github.com/cncf/udpa/go v0.0.0-20220112060539-c52dc94e7fbe // indirect`

**Comment by ldez** [comment]
NO

**Comment by 100vlx** [comment]
> 

Sorry, I meant would you like to release a new release version? Use the current main branch

**Comment by ldez** [comment]
No, I don't want to create a new release only for that, as I already said you don't need it.
